# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
after_success:
# push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("LazyContext")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
# build documentation
  - julia -e 'cd(Pkg.dir("LazyContext")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
